# Generated by Django 2.2.10 on 2020-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[(1, 'USER_RIGISTERD_COUPON')], max_length=50, null=True),
        ),
    ]
